service: serverless-employee-portal-service 
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.employeeTableName}
custom:
  employeeTableName: employee-table-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  createPost:
    handler: app.createEmpCertificate
    name: employee-certificate-post
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/certificate
          method: POST
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn
  updatePost:
    handler: app.updateEmpCertificate
    name: employee-certificate-update
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http:
          path: employee/certificate/{empId}
          method: PUT
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn
resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTableName}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1