service: serverless-employee-portal-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  region: ap-south-1
  environment:
    EMPLOYEE_TABLE: ${self:custom.employeeTableName}
custom:
  employeeTableName: certificateDetails-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  createPost:
    handler: app.employeeCertificate
    name: employee-certificate-post
    memorySize: 128
    timeout: 5
    events:
      - http:
          method: POST
          path: employee/certificate
          cors: true
      - http:
          method: PUT
          path: employee/certificate/{empId}
          cors: true
resources:
  Resources:
    createPost:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTableName}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
